sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer
  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git ~/wordpress-coding-standards
  - gem update --system
  - gem install compass

script:
  - phpcs --config-set installed_paths ~/wordpress-coding-standards
  - phpcs --standard=wordpress-extra --extensions=php --ignore=node_modules  -n -s .
  - grunt